import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/providers/StoreProvider'
import ThemeProvider from '@/providers/ThemeProvider'
import PopupDismissProvider from '@/providers/PopupDismissProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <ThemeProvider>
        <PopupDismissProvider>
          <html lang='en'>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-base-100`}
            >
              {children}
            </body>
          </html>
        </PopupDismissProvider>
      </ThemeProvider>
    </StoreProvider>
  )
}
